import { Card, CategoryInfo, Badge } from "./types";

export const CATEGORIES: Record<string, CategoryInfo> = {
  pioneers: {
    id: "pioneers",
    label: "Cosmic Pioneers",
    symbol: "🔮",
    tagline: "Inspiring Women & Visionaries",
    bgColor: "bg-amber-950/40",
    textColor: "text-amber-300",
    accentColor: "bg-amber-500",
    hoverColor: "hover:bg-amber-500/10",
    borderColor: "border-amber-500/30",
    gradient: "from-amber-500/15 via-yellow-500/10 to-emerald-500/10",
    glowColor: "shadow-amber-500/20",
    description: "Famous female astronomers, mathematical minds, and pioneering astronauts who paved the highway to the stars.",
  },
  wonders: {
    id: "wonders",
    label: "Stellar Wonders",
    symbol: "💖",
    tagline: "Nebulae, Exoplanets & Voids",
    bgColor: "bg-emerald-950/40",
    textColor: "text-emerald-300",
    accentColor: "bg-emerald-500",
    hoverColor: "hover:bg-emerald-500/10",
    borderColor: "border-emerald-500/30",
    gradient: "from-emerald-500/15 via-teal-500/10 to-amber-500/10",
    glowColor: "shadow-emerald-500/20",
    description: "Breathtaking space phenomena, hyper-massive black holes, glowing star birth nurseries, and enigmatic alien worlds.",
  },
  quests: {
    id: "quests",
    label: "Milestone Quests",
    symbol: "🩵",
    tagline: "Voyages into the Dark Page",
    bgColor: "bg-yellow-950/40",
    textColor: "text-yellow-300",
    accentColor: "bg-yellow-500",
    hoverColor: "hover:bg-yellow-500/10",
    borderColor: "border-yellow-500/30",
    gradient: "from-yellow-500/15 via-amber-500/10 to-emerald-500/10",
    glowColor: "shadow-yellow-500/20",
    description: "Deep space probes, daring planetary landers, and cosmic journeys that carried human curiosity farther than ever before.",
  },
  tech: {
    id: "tech",
    label: "Celestial Tech",
    symbol: "💛",
    tagline: "Engines, Suits & Telescopes",
    bgColor: "bg-emerald-950/30",
    textColor: "text-emerald-400",
    accentColor: "bg-emerald-500",
    hoverColor: "hover:bg-emerald-500/10",
    borderColor: "border-emerald-500/20",
    gradient: "from-emerald-500/15 via-teal-500/10 to-yellow-500/10",
    glowColor: "shadow-emerald-500/20",
    description: "Intricate spacesuits, chemical and ion rocket thrusters, space station capsules, and golden-mirrored observatories.",
  },
};

export const INITIAL_CARDS: Card[] = [
  // pioneers
  {
    id: "pioneer-sally-ride",
    category: "pioneers",
    title: "Dr. Sally Ride",
    frontInfo: "Who was the first American woman to launch into space, and what scientific subject did she teach?",
    backInfo: "Dr. Sally Ride was an absolute powerhouse! In 1983 she made history aboard the Challenger. She was also a brilliant physicist with a PhD from Stanford and spent years championing science specifically for young girls.",
    funFact: "She was an elite ranked tennis player before devoting her life to astrophysics and space flight!",
    difficulty: "easy",
  },
  {
    id: "pioneer-katherine-johnson",
    category: "pioneers",
    title: "Katherine Johnson",
    frontInfo: "Whose incredible math calculations mapped the orbits for the Apollo 11 moon landing?",
    backInfo: "Katherine Johnson was a legendary NASA mathematician! Overcoming severe racial and gender barriers, her hand-calculated equations were so perfect that astronaut John Glenn refused to fly until Katherine herself verified the computer's math.",
    funFact: "She graduated from high school at age 14 and college at age 18, showing a legendary gift for mathematics early on!",
    difficulty: "medium",
  },
  {
    id: "pioneer-mae-jemison",
    category: "pioneers",
    title: "Dr. Mae Jemison",
    frontInfo: "Who was the first Black woman in space, and what are her other amazing professional fields?",
    backInfo: "Dr. Mae Jemison blasted off on space shuttle Endeavour in 1992. Beyond astronaut training, she's a medical doctor who served in the Peace Corps, an environmental engineer, and an elegant dancer!",
    funFact: "She always brought art, poetry, and a poster from the Dance Theatre of Harlem with her into the orbital spacecraft!",
    difficulty: "easy",
  },
  {
    id: "pioneer-nancy-roman",
    category: "pioneers",
    title: "Nancy Grace Roman",
    frontInfo: "Who was NASA's first female executive, famously known as the 'Mother of Hubble'?",
    backInfo: "Nancy Grace Roman was NASA's first Chief of Astronomy. She single-handedly planned the space telescope programs and successfully secured the massive funding and technical setup for the Hubble Space Telescope.",
    funFact: "When she was in 5th grade, she organized a neighborhood astronomy club with her friends to study constellations!",
    difficulty: "medium",
  },
  {
    id: "pioneer-ellen-ochoa",
    category: "pioneers",
    title: "Dr. Ellen Ochoa",
    frontInfo: "Who is the first Hispanic woman in space, and what is her musical hobby?",
    backInfo: "Dr. Ellen Ochoa flew a 9-day mission in 1993 to study Earth's ozone layer. She went on to become the Director of NASA's Johnson Space Center. She is also a patent-holding optical systems researcher and a classical flutist!",
    funFact: "She actually played her classical flute while weightless in space, performing to the gorgeous orbital view!",
    difficulty: "easy",
  },

  // wonders
  {
    id: "wonder-pillars",
    category: "wonders",
    title: "Pillars of Creation",
    frontInfo: "What are these giant, tower-like dust columns located in the Eagle Nebula, and what happens inside them?",
    backInfo: "These are magnificent, light-years-tall columns of cool interstellar gas and dust. They are stellar nurseries, where gravity pulls gas together to ignite and create brand-new stars!",
    funFact: "The columns look solid but are actually semi-transparent clouds, glowing from the energetic radiation of newborn stars inside!",
    difficulty: "medium",
  },
  {
    id: "wonder-enceladus",
    category: "wonders",
    title: "Moon Enceladus",
    frontInfo: "Which tiny, ice-covered moon of Saturn sprays giant geysers of liquid water out into the cold dark of space?",
    backInfo: "Enceladus is Saturn's sixth-largest moon. Beneath its global reflective ice sheet lies a warm, salty ocean. Geothermal vents spray vapor plume fountains containing core nutrients for potential alien microbes!",
    funFact: "The geyser spray from Enceladus is so massive and powerful that some of it escapes to form one of Saturn's glowing rings!",
    difficulty: "hard",
  },
  {
    id: "wonder-trappist",
    category: "wonders",
    title: "TRAPPIST-1e",
    frontInfo: "What makes this particular Earth-sized exoplanet, located 40 light-years away, highly exciting to scientists?",
    backInfo: "TRAPPIST-1e orbits a cool dwarf star in the 'Goldilocks Zone' (habitable zone). It's rocky, has stellar conditions to hold liquid ocean water, and could potentially host life, making it a critical research focus for modern telescopes.",
    funFact: "TRAPPIST-1 is a system of 7 sibling planets huddled so close together that from one's surface, the others look like huge pastel moons!",
    difficulty: "hard",
  },
  {
    id: "wonder-sagittarius",
    category: "wonders",
    title: "Sagittarius A*",
    frontInfo: "What massive mystery object sits at the exact center of our Milky Way Galaxy, holding 4 million times our Sun's mass?",
    backInfo: "This is a supermassive black hole around which our entire galaxy rotates. It is completely invisible because its immense gravity prevents light from escaping, but its massive silhouette was photographed in 2022!",
    funFact: "Despite its enormous mass, it fits inside a diameter that is smaller than the orbit of Mercury around our Sun!",
    difficulty: "medium",
  },

  // quests
  {
    id: "quest-apollo11",
    category: "quests",
    title: "Apollo 11",
    frontInfo: "What was the iconic objective of the 1969 Apollo 11 flight, and which module safely returned the astronauts?",
    backInfo: "Apollo 11 carried humans to walk on the Moon for the first time. While Neil Armstrong and Buzz Aldrin stepped onto lunar dust, Michael Collins orbited in the 'Columbia' Command Module, which safely flew them home to Earth.",
    funFact: "Apollo 11's guidance computer was less powerful than a modern car key fob or smartphone!",
    difficulty: "easy",
  },
  {
    id: "quest-voyager",
    category: "quests",
    title: "Voyager 1",
    frontInfo: "Which spacecraft, launched in 1977, has traveled the furthest from Earth into interstellar deep space?",
    backInfo: "Voyager 1 is our ultimate traveler! After photographing Jupiter's storms and Saturn's rings, it breached the Sun's magnetic boundary (heliopause) in 2012, sailing indefinitely into the cosmic interstellar ocean.",
    funFact: "It carries a 'Golden Record' containing recordings of Earth's ocean sounds, system music, and greetings in 55 human languages!",
    difficulty: "hard",
  },
  {
    id: "quest-artemis",
    category: "quests",
    title: "Artemis Program",
    frontInfo: "What is NASA's modern lunar exploration program, and what historic milestone will its crew achieve?",
    backInfo: "Named after Apollo's twin sister, Artemis is NASA's current program. It aims to build a sustainable camp on the Moon and safely land both the very first woman and the very first person of color on the lunar surface!",
    funFact: "The program will use a unique orbiting outpost called 'Gateway' to act as a workspace and launchpad for Mars missions!",
    difficulty: "easy",
  },
  {
    id: "quest-jwst",
    category: "quests",
    title: "James Webb Telescope",
    frontInfo: "What giant space observatory, equipped with gold-plated mirrors, can look back 13.5 billion years to see the first galaxies?",
    backInfo: "The JWST is the world's premier space telescope. It works in infrared light (heat), which lets it peer directly through the thick dust clouds blocking visible light. Its 18 gold hexagonal mirrors work as a giant cosmic magnifying glass.",
    funFact: "It operates in a super cold spot in space called Lagrange Point 2, protected by a five-layer sunshield thin as a hair!",
    difficulty: "medium",
  },

  // tech
  {
    id: "tech-spacesuit",
    category: "tech",
    title: "EMU Spacesuit",
    frontInfo: "Why is a modern NASA spacewalking suit described as an individual, self-contained spacecraft?",
    backInfo: "The Extravehicular Mobility Unit (EMU) has 14 complex layers of materials to insulate astronauts against extreme thermal sweeps (-250°F to 250°F), holds a pressurized oxygen tank, a drink bladder, radio lines, and blocks micrometeoroids.",
    funFact: "Inside their helmet, astronauts have a tiny piece of Velcro so they can scratch their nose during long spacewalks!",
    difficulty: "medium",
  },
  {
    id: "tech-ionthruster",
    category: "tech",
    title: "Ion Propulsion",
    frontInfo: "How do futuristic deep-space probes generate speed using electric fields and rare gases instead of combustion?",
    backInfo: "Ion thrusters create thrust by stripping electrons from noble gases like Xenon to create charged ions. Strong electric fields accelerates these ions out of the exhaust at speeds up to 90,000 mph, gently accelerating probes for years.",
    funFact: "The thrust is incredibly gentle—comparable to the weight of a single sheet of paper resting in your hand!",
    difficulty: "hard",
  },
  {
    id: "tech-canadarm",
    category: "tech",
    title: "Canadarm2",
    frontInfo: "What is the massive robotic arm on the International Space Station, and how does it move around?",
    backInfo: "Canadarm2 is a 57-foot-long robotic arm that performs heavy repairs and catches sailing cargo crafts. Remarkably, it can crawl end-over-end like an inchworm to different mounting ports on the station's exterior!",
    funFact: "It has seven joints that mimic the flexible human arm, but both ends can act as hands or shoulders depending on attachment!",
    difficulty: "medium",
  },
];

export const STEM_BADGES: Badge[] = [
  {
    id: "nebula-novice",
    title: "Nebula Novice",
    description: "Successfully explore and flip your very first interactive flashcard.",
    requirement: "Flip 1 card",
    emoji: "🔮",
    category: "study",
  },
  {
    id: "constellation-conqueror",
    title: "Supernova Scholar",
    description: "Mark 5 space flashcards as completely Mastered.",
    requirement: "Master 5 cards",
    emoji: "🌟",
    category: "study",
  },
  {
    id: "badge-stella-friend",
    title: "Stella's Apprentice",
    description: "Ask a question and converse with Stella, your Cosmic Guide.",
    requirement: "Send 1 chat message to Stella",
    emoji: "💬",
    category: "ai",
  },
  {
    id: "badge-alchemist",
    title: "Cosmic Creator",
    description: "Generate a custom, AI-powered flashcard to expand your custom collection.",
    requirement: "Generate 1 card using Gemini",
    emoji: "🎨",
    category: "ai",
  },
  {
    id: "badge-lunar-path",
    title: "Artemis Explorer",
    description: "Undertake a Space Quiz and score at least 3 correct answers.",
    requirement: "Score 3+ in a single Quiz",
    emoji: "🚀",
    category: "quiz",
  },
  {
    id: "badge-starlight-perfection",
    title: "Cosmic Perfectionist",
    description: "Get a perfect score of 100% on any Space Exploration Quiz!",
    requirement: "Score 5/5 on any Quiz",
    emoji: "👑",
    category: "quiz",
  },
];
